# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# to handle CloudFlare tunnels
http:
  trusted_proxies: 192.168.68.12
  use_x_forwarded_for: true

